# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: start_ofs.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstart_ofs.proto\x12\rharmonyServer\"\x8a\x02\n\x08StartOFS\x12\x12\n\nscenarioId\x18\x01 \x02(\t\x12.\n\x06inputs\x18\x02 \x02(\x0b\x32\x1e.harmonyServer.StartOFS.Inputs\x12\x30\n\x07outputs\x18\x03 \x02(\x0b\x32\x1f.harmonyServer.StartOFS.Outputs\x1ai\n\x06Inputs\x12\x14\n\x0cScenarioName\x18\x01 \x02(\t\x12\x14\n\x0cSettingsFile\x18\x02 \x02(\t\x12\x17\n\x0f\x41imsunModelFile\x18\x03 \x02(\t\x12\x1a\n\x12PathAssignmentFile\x18\x04 \x02(\t\x1a\x1d\n\x07Outputs\x12\x12\n\nOFSResults\x18\x01 \x02(\t')



_STARTOFS = DESCRIPTOR.message_types_by_name['StartOFS']
_STARTOFS_INPUTS = _STARTOFS.nested_types_by_name['Inputs']
_STARTOFS_OUTPUTS = _STARTOFS.nested_types_by_name['Outputs']
StartOFS = _reflection.GeneratedProtocolMessageType('StartOFS', (_message.Message,), {

  'Inputs' : _reflection.GeneratedProtocolMessageType('Inputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTOFS_INPUTS,
    '__module__' : 'start_ofs_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartOFS.Inputs)
    })
  ,

  'Outputs' : _reflection.GeneratedProtocolMessageType('Outputs', (_message.Message,), {
    'DESCRIPTOR' : _STARTOFS_OUTPUTS,
    '__module__' : 'start_ofs_pb2'
    # @@protoc_insertion_point(class_scope:harmonyServer.StartOFS.Outputs)
    })
  ,
  'DESCRIPTOR' : _STARTOFS,
  '__module__' : 'start_ofs_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StartOFS)
  })
_sym_db.RegisterMessage(StartOFS)
_sym_db.RegisterMessage(StartOFS.Inputs)
_sym_db.RegisterMessage(StartOFS.Outputs)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STARTOFS._serialized_start=35
  _STARTOFS._serialized_end=301
  _STARTOFS_INPUTS._serialized_start=165
  _STARTOFS_INPUTS._serialized_end=270
  _STARTOFS_OUTPUTS._serialized_start=272
  _STARTOFS_OUTPUTS._serialized_end=301
# @@protoc_insertion_point(module_scope)
