# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stop.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='stop.proto',
  package='harmonyServer',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=b'\n\nstop.proto\x12\rharmonyServer\"\"\n\tStopModel\x12\x15\n\rexperiment_id\x18\x01 \x02(\t'
)




_STOPMODEL = _descriptor.Descriptor(
  name='StopModel',
  full_name='harmonyServer.StopModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='experiment_id', full_name='harmonyServer.StopModel.experiment_id', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=63,
)

DESCRIPTOR.message_types_by_name['StopModel'] = _STOPMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StopModel = _reflection.GeneratedProtocolMessageType('StopModel', (_message.Message,), {
  'DESCRIPTOR' : _STOPMODEL,
  '__module__' : 'stop_pb2'
  # @@protoc_insertion_point(class_scope:harmonyServer.StopModel)
  })
_sym_db.RegisterMessage(StopModel)


# @@protoc_insertion_point(module_scope)
